@startuml

object "<u>:App" as o1
object "<u>myDongle:BluetoothIO" as o2
object "<u>:ReadAcctView" as o3

o2 : privateKey = "NNUWC3TPN5ZWQCQ="
o2 : publicKey = "OJXWG23TBI======"
o2 : dongleAddress = "0123456789AB"

o3 : acct = array(["username", "foo@bar.com"], ...)

o1 "owner" -- o2 : owns
o3 "sender" -- o2 : sends string to inject to
'o1 "user \n interface" -- o2 : has reference to
'o2 "owner" -- o3 : stores
'o3 "parent" -- o4 : owns

@enduml
