@startuml
package MobileAppSubsystem <<rectangle>> {
        object "<u>:DBLoginView" as o1
        object "<u>:App" as o2
        object "<u>:Database" as o3
}

o2 : pass = "aec070645fe53ee3b3763059376134f058cc337247c978add178b6ccdfb0019f"
o3 : dbpass = "aec070645fe53ee3b3763059376134f058cc337247c978add178b6ccdfb0019f"

o2 --> o1 : initializes
o1 ..> o2 : returns password hash
o2 -- o3 : checks for matching password hash
'o1 "user \n interface" -- o2 : has reference to
'o2 "owner" -- o3 : stores
'o3 "parent" -- o4 : owns

@enduml
