@startuml
actor DeviceUser as a1

rectangle app {
        usecase AddGroup as u1
        usecase EditGroupMetadata as u2
        usecase EditDatabase as u3
}

a1 --> u1
u2 ..> u1 : <<include>>
u1 --> u3
@enduml
